app:
  # Should be the same as backend.baseUrl when using the `app-backend` plugin.
  baseUrl: ${BASE_URL}

backend:
  # Note that the baseUrl should be the URL that the browser and other clients
  # should use when communicating with the backend, i.e. it needs to be
  # reachable not just from within the backend host, but from all of your
  # callers. When its value is "http://localhost:7007", it's strictly private
  # and can't be reached by others.
  baseUrl: ${BASE_URL}
  # The listener can also be expressed as a single <host>:<port> string. In this case we bind to
  # all interfaces, the most permissive setting. The right value depends on your specific deployment.
  listen: ':7007'

  # config options: https://node-postgres.com/api/client
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      ssl:
        ca: ${PGBOUNCER_CA_ROOT}

  reading:
    allow:
      - host: 'holos.run'
      - host: '*.holos.run'
      - host: 'openinfrastructure.co'
      - host: '*.openinfrastructure.co'

auth:
  environment: production
  providers:
    guest: null
    # oauth2Proxy:
    #   signIn:
    #     resolvers:
    #       - resolver: emailMatchingUserEntityProfileEmail
    holosProxy:
      issuer: https://login.holos.run
      audience: "269746002573969304"
      oidcIdTokenHeader: "x-oidc-id-token"
      signIn:
        resolvers:
          - resolver: emailMatchingUserEntityProfileEmail
          - resolver: signInWithoutCatalogUser


catalog:
  # Overrides the default list locations from app-config.yaml
  # Refer to https://backstage.io/docs/features/software-catalog/#adding-components-to-the-catalog
  #
  # NOTE: In production, CWD is /app  This is different than development where
  # CWD is ./packages/backend, As a result, entries cannot be copied verbatim
  # from app-config.yaml otherwise they will not resolve to the correct location.
  locations:
    # Initial iam User and Group data is expected to be provided in the Secret.
    # Local example data, file locations are relative to the backend process, typically `packages/backend`
    - type: file
      target: /app/iam.yaml
      rules:
        - allow: [User, Group]
