#! /bin/bash
#

set -xeuo pipefail

yarn tsc
yarn build:backend --config ../../app-config.yaml
# Build the image
docker image build . -f packages/backend/Dockerfile --tag quay.io/holos-run/portal:latest
docker push quay.io/holos-run/portal:latest
